Add testing output
Add testing program output, add log file functionality for extensive information about errors and failed tests.

diff --git a/unit-test b/unit-test
--- a/unit-test
+++ b/unit-test
@@ -27,22 +27,35 @@
 #                  Author:  Max Zhuravsky <paperlark@yandex.ru>                  #
 ##################################################################################
 
-
-# Test suit integrity error
-int_err() {
+# Exit with integrity error
+integrity_error() {
     echo '> error: test suit integrity error'
     exit 4
+}
+
+# Check whether the state of the parser is as expected
+check_state() {
+    if [ $# -eq 0 ]; then
+        echo '> error: wrong number of arguments for checker'
+        exit 5
+    elif [ "$1" -ne $STATE ]; then
+        integrity_error    
+    fi
 }
 
 # Process tests from the file
 process() {
 
-    # Initialize variables 
-    ARGS=""
-    CURRENT_TEST=0
-    STATE=0 # 0 - initial state, 1 - suit running, 2 - test running 
+    # Initialize variables and files
+    LOG_FILE='log.test'
+    echo -e 'Error Log:\n' > "${LOG_FILE}"
+    TEST_ARGS=''
+    TEST_NUM=0
+    EXPECTED_RESULT=''
+    RECEIVED_RESULT=''
+    STATE=0 # 0 - initial state, 1 - inside suit, 2 - inside test, 3 - inside result 
     LEN=${#CONTENTS[@]}
-
+    
     # Examine suit file line by line
     for (( i = 0; i < LEN; i++ )); do
 
@@ -50,48 +63,73 @@ process() {
        CONTENTS[$i]=`echo "${CONTENTS[$i]}" | sed -e 's/^[ \t]*//'`
 
         # Process line
-        if [ "${CONTENTS[$i]}" == '<Suit>' ]; then # Suit started
-            if [ "${STATE}" -ne 0 ]; then
-                int_err
-            fi
+        if [ "${CONTENTS[$i]}" == '<Suit>' ]; then # Suit section found
+            check_state 0
             STATE=1
-        elif [ "${CONTENTS[$i]}" == '<Test>' ]; then # Test start found
-            if [ "${STATE}" -ne 1 ]; then
-                int_err
-            fi
+        elif [ "${CONTENTS[$i]}" == '<Test>' ]; then # Test section found
+            check_state 1
             STATE=2
             ARGS=""
-            (( CURRENT_TEST++ ))        
-        elif [ "${CONTENTS[$i]}" == '</Test>' ]; then # Test end found
-            if [ "${STATE}" -ne 2 ]; then
-                int_err
-            fi
+            (( TEST_NUM++ ))        
+        elif [ "${CONTENTS[$i]}" == '</Test>' ]; then # Test section ended
+            check_state 2
             STATE=1
-            echo -e "> test #${CURRENT_TEST} with arguments: \"`echo ${ARGS} | sed -e 's/[\t\n]*/ /' | sed -e 's/^ *//'`\" is running..."
-            echo '> unit output:'
-            ./"${BINARY}" <<< "${ARGS}"
+            echo -e "> test #${TEST_NUM} with arguments: \"`echo ${ARGS} | sed -e 's/[\t\n]*/ /' | sed -e 's/^ *//'`\" is running..."            
+            RECEIVED_RESULT=`./"${BINARY}" <<< "${ARGS}"`
             EXIT_CODE="$?"
-            if (( EXIT_CODE == 0 )); then
-                echo '> test succesfully completed'
-            else
-                echo '> test failed!'
-                FAILED="${FAILED}#${CURRENT_TEST} "
+
+            if (( EXIT_CODE != 0 )); then # Error return code
+                # Print log message to the file
+                echo "> test #${TEST_NUM} failed with code $EXIT_CODE" >> "${LOG_FILE}"
+                if [ "${FAILED}" != "" ]; then
+                    FAILED="${FAILED}, "
+                fi
+                FAILED="${FAILED}#${TEST_NUM}"
+            elif [ "${EXPECTED_RESULT}" != "${RECEIVED_RESULT}" ]; then # Wrong answer
+                # Print log message to the log file
+                echo "> test #${TEST_NUM} failed: result does not match the expected" >> "${LOG_FILE}"
+                echo '> expected:' >> "${LOG_FILE}"
+                echo "${EXPECTED_RESULT}" >> "${LOG_FILE}"
+                echo '> result:' >> "${LOG_FILE}"
+                echo "${RECEIVED_RESULT}" >> "${LOG_FILE}"
+                echo >> "${LOG_FILE}"
+
+                if [ "${FAILED}" != "" ]; then
+                    FAILED="${FAILED}, "
+                fi
+                FAILED="${FAILED}#${TEST_NUM}"
             fi
-        elif [ "${CONTENTS[$i]}" == '</Suit>' ]; then # Test suit end found
+        elif [ "${CONTENTS[$i]}" == '<Result>' ]; then # Result section found
+            check_state 2
+            STATE=3
+            EXPECTED_RESULT=""
+        elif [ "${CONTENTS[$i]}" == '</Result>' ]; then # Result section ended
+            check_state 3
+            STATE=2
+        elif [ "${CONTENTS[$i]}" == '</Suit>' ]; then # Test suit section ended
             if [ "${STATE}" -ne 1 ]; then
-                int_err
+                integrity_error
             fi
             STATE=0
         else # Argument or empty line found
-            if [ "${STATE}" -ne 2 ] && [ "${CONTENTS[$i]}" != '' ]; then
-                int_err
+            if [ "${STATE}" -eq 2 ]; then
+                if [ "${ARGS}" != "" ]; then
+                    ARGS=${ARGS}$'\n'
+                fi
+                ARGS=${ARGS}${CONTENTS[$i]}
+            elif [ "${STATE}" -eq 3 ]; then
+                if [ "${EXPECTED_RESULT}" != "" ]; then
+                    EXPECTED_RESULT=${EXPECTED_RESULT}$'\n'
+                fi
+                EXPECTED_RESULT=${EXPECTED_RESULT}${CONTENTS[$i]}
+            elif [ "${CONTENTS[$i]}" != "" ]; then
+                integrity_error
             fi
-            ARGS="${ARGS}${CONTENTS[$i]}"$'\n'
         fi
     done
 
     if [ ${STATE} -ne 0 ]; then # Test suit end was not found
-        int_err
+        integrity_error
     fi
 }
 
@@ -125,5 +163,5 @@ echo '> unit testing has finished!'
 if [ FAILED == "" ]; then
     echo '> all tests are successfully passed'
 else
-    echo "> test(s) ${FAILED}were failed"
+    echo "> test(s) ${FAILED} were failed"
 fi
